# Generated by Django 4.0.4 on 2022-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company'), ('admin', 'Admin'), ('manager', 'Manager')], default='user', max_length=40),
        ),
    ]
