# Generated by Django 4.0.4 on 2022-05-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
