# Generated by Django 4.0.4 on 2022-06-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiaries', '0005_rename_ishidden_apiary_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='blue', max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.BooleanField(default='active', max_length=255)),
                ('bees_family', models.CharField(default='Apidae', max_length=255)),
                ('number', models.IntegerField()),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='apiaries.apiary')),
            ],
        ),
    ]
