# Generated by Django 4.0.4 on 2022-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
