# Generated by Django 3.2.13 on 2022-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0002_alter_hive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='bees_family',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hive',
            name='color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hive',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hive',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
