# Generated by Django 4.0.4 on 2022-05-29 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiaries', '0003_alter_apiary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiary', to=settings.AUTH_USER_MODEL),
        ),
    ]
