# Generated by Django 4.0.4 on 2022-06-03 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiaries', '0005_rename_ishidden_apiary_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiary',
            name='location',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='status',
            field=models.CharField(default='test', max_length=55),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
